### PR TITLE
Fix install on linux 

### LINKED ISSUE #13: Installation does not work on linux
Currently installing aria2 on linux just downloads the source code.

### PR DESCRIPTION
**Pull request by bradym**
Updated to compile code after downloading on linux. Also added note to readme about some features needing libraries available at compile time.

Fixes #13

### CODE REVIEW

**Comment by smorimoto** [comment]
It might be a better choice to build from source in all contexts.

**Comment by smorimoto** [comment]
Anyway, I just rebased to the latest master.

**Comment by bradym** [comment]
Ran `shfmt` and pushed to my branch to address the failing checks.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Anyway, this looks good! Thanks @bradym!

**Pull request merged**
